version: "3"

dotenv: [.env]

tasks:
  cp-wasm:
    desc: "Copy wasm files and build the project"
    cmds:
      - echo $BLVE_PATH
      - cd $BLVE_PATH && make build-web && cd -
      - rm -r ./src/wasm/ || true
      - mkdir ./src/wasm/
      - cp $BLVE_PATH/npm-pkg/src/runtime/index.ts ./src/runtime/index.ts
      - cp -r $BLVE_PATH/crates/blve_compiler/pkg/* ./src/wasm/
      - vite dev --force
