version: "3"

dotenv: [.env]

tasks:
  cp-wasm:
    desc: "Copy wasm files and build the project"
    cmds:
      - echo $LUNAS_PATH
      - cd $LUNAS_PATH && task build-web && cd -
      - rm -r ./src/wasm/ || true
      - mkdir ./src/wasm/
      - cp $LUNAS_PATH/npm-pkgs/lunas/src/runtime/index.ts ./src/runtime/index.ts
      - cp -r $LUNAS_PATH/crates/lunas_compiler/pkg/* ./src/wasm/
      - vite dev --force
